### ISSUE TITLE
toast not rendered properly on page after NProgress executed

### ISSUE THREAD

**Issue by wychoong** [jerrywu001/vue3-toastify#11]
I have a vue page build with Laravel Inertiajs

after having page interactions with backend, which will trigger Inertiajs' [progress loading ](https://inertiajs.com/progress-indicators) bar, which is NProgress under the hood. toastify styling is broken

these are the rendered toast
```html
<div id="rbkw9fi" class="Toastify__toast Toastify__toast-theme--nprogress-busy Toastify__toast--success" data-testid="toast-item-rbkw9fi">
<div id="h974b8c" class="Toastify__toast Toastify__toast-theme-- Toastify__toast--warning" data-testid="toast-item-h974b8c">
```

these are the class when before having any inertiajs progress loading
`Toastify__toast Toastify__toast-theme--light Toastify__toast--warning`

i tested to disable inertiajs progress loading bar, the issue is gone, but that's not the solution. any help?

**Comment by esemplare** [comment]
Looks like it could be due to nprogress adding nprogress-busy to the documentElement classes.

https://github.com/rstacruz/nprogress/blob/master/nprogress.js#L227
```
/**
   * (Internal) renders the progress bar markup based on the `template`
   * setting.
   */

  NProgress.render = function(fromStart) {
    if (NProgress.isRendered()) return document.getElementById('nprogress');

    addClass(document.documentElement, 'nprogress-busy');

    var progress = document.createElement('div');
```

And vue3-toastify using the documentElement classes for the theme when auto.

https://github.com/jerrywu001/vue3-toastify/blob/a855bd390bfcbda9abe582fa277469286afac577/src/core/toast.tsx#L66-L68
https://github.com/jerrywu001/vue3-toastify/blob/a855bd390bfcbda9abe582fa277469286afac577/src/utils/tools.ts#L59

**Comment by jerrywu001** [comment]
would you like to create a pr?

**Comment by wychoong** [comment]
@esemplare yes you are correct, that is what causing the issue.
 also after nprogress removed its nprogress-busy class, it also left behind a empty space `class=" "` which causes toastify to get the wrong empty theme

suggestion will be checking if the documentElement contain allowed theme (dark, light...) and also .trim()

**Comment by esemplare** [comment]
Since I'm not familiar enough with how other libraries affect the documentElement classes, I might suggest to use media queries for 'prefers-color-scheme' and switch based off light/dark.

`window.matchMedia('(prefers-color-scheme: dark)')`

https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#Methods

Can also add an event listener to detect when this preference changes.

https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/change_event

**Comment by jerrywu001** [comment]
thanks a lot. @esemplare
