### ISSUE TITLE
Toast options don't affect toast.promise

### ISSUE THREAD

**Issue by FabianB12** [jerrywu001/vue3-toastify#18]
Hey, it seems that specifying options on toast.promise does not actually do anything. It'd be nice to have support for autoClose & dismiss on click for those as well.

**Comment by jerrywu001** [comment]
By design, loading or promise is only a transition state, and some attributes are read-only. You can use `toast.update` to change status.

See: https://vue3-toastify.js-bridge.com/usage/promise.html 

![image](https://github.com/jerrywu001/vue3-toastify/assets/12525415/37c66243-ac83-4fd7-9123-057715fdb481)

TIPS: promise use the loading function

![image](https://github.com/jerrywu001/vue3-toastify/assets/12525415/67ed5e9f-dee9-499e-a954-32695697cc62)

**Comment by jerrywu001** [comment]
And other props like `delay` can take effect

```jsx
toast.loading(
  'Please wait...',
  {
    position: toast.POSITION.BOTTOM_RIGHT,
    delay: 3000,
  },
);
```

**Comment by jerrywu001** [comment]
the latest version 0.1.13 supports autoClose/closeOnClick when the promise is finished. @CavalcanteLeo @FabianB12
